spring:
    profiles.active: test

---
server:
  port: 33333

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:30101/eureka/

zuul:
  routes:
    #用户权限管理中心
    ussp-uc:
      path: /uc/**
      serviceId: ussp-uc-app
    #车全系统
    cisp-web-service:
      path: /admin/**
      serviceId: cisp-web-service
      sensitiveHeaders: "*"
    cisp-car-service:
      path: /car/**
      serviceId: cisp-car-service
#风控系统
    risk-ui:
      path: /rule/ui/**
      serviceId: risk-ui
    rule-service:
      path: /rule/service/**
      serviceId: rule-service
    risk-activiti:
      path: /activiti/**
      serviceId: risk-activiti-service
    risk-drools:
      path: /drools/**
      serviceId: risk-drools
gateway:
  security: 
    jwt: 
      tokenExpirationTime: 29  #分钟
      refreshTokenExpTime: 720
      tokenIssuer: qiuwenwu@hongte.info
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
ht:
  ignoreUrl: #不验证的url(可以使用通配符（*）)
     web: /uc/echo,/admin/*,/car/*,/rule/ui/* #不需要验证token
     http: /auth/loadBtnAndTab,/auth/loadMenu,/check/key #需要验证token
