from: dev

---
spring:
  data:
    mongodb:
      password: 123456
      database: EIP-DEV
      authentication-database: admin
      port: 27017
      host: 10.110.1.240
      username: root
  http:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
      enabled: true
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  messages:
    basename: i18n/messages
  redis:
    password: tuandai
    database: 1
    port: 6379
    host: 10.110.1.240
    timeout: 1000
server:
  context-path: /eip
  port: 30406
  tomcat:
    uri-encoding: UTF-8
context: out-service

eip:
  td:
    tdUserName: td_xiaodai
    zcfz:
      ivParameter: f5d2e2g5y2d1s1r6
      userPwd: e9435314d362b0bba672be73634766ff
      sKey: 4s5d7r1h2q6o1h3l
      userName: fangdai
      url: http4://10.100.12.155:8080/
    url: http4://121.13.249.210:19301/
    key: MJNdwerlobvURRJHitgYTEYKopI
  camel:
    http:
      normal:
        timeout: 1000
      middle:
        timeout: 3000
      large:
        timeout: 7000
      huge:
        timeout: 15000
  sms:
    password: fQ8i461Q
    uri: 211.147.239.62:9051/api/v1.0.0/message/mass/send
    username: cqqc@dgtdw
  tc:
    blackList:
      privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJj0nhlKUwiBH0Xh0kAmuHMqBQWFLwbBqHEqAsFzJpAq/j9IeiMa4Y2o/uXckThzrmeA3pfVP4/1HtcLUrQ7u4qxs9c/xh2urtgz0jHw/ObMgx9mnNH7A5ED810uUnSD1fwtVKfmg+JSn6HY4bmZjZ6+7eZAwRWDgyWlBy2CDqdNAgMBAAECgYEAlqIhqUp3J6LyR4Iz65W2hURWma8mNwM1fe0ftaBP1B9jMLOSBUyN4VMTZRCpu+zBT5Gspd8PsBh4/NNb6cAB2vktgzd1w1I2aCxCprtpZ/9BJ255pAJnWKqWGar5w0wDeFfMrMSQWQubXw56k2kZQl4JOvZxIjty57V8yoNbL0kCQQDO6Ioc+MfOp7Al6vzjYvpPClm7jvAgV60INTPMaEkY/P46wIuYcOzb3KK84jOeEaA0quEx8gVpeuMYKS+zEQifAkEAvT8GEeSz0tY1neV7XIhCfsCX2YU6xeHQSVSndmI3Qw++LbSsK29Yk6S45YZhuQVCCxGN/tb2GHkRZ6b+QpjMkwJBAMpjKd3G92LMIgAlCDK/uUohPL66xWVNfaJ+r+ksxPudVGxRtPpq0zUIb2LE/GqMoSGDWH3LV8Hig0o51z+X1M8CQCzMcIln1FHCt6qLGmrLLsKGoOuzKDiTvhS9326czWwom+KB9IfLsfIxejuLVjLQVdP88doz1MnyTvZ0h5gIR9UCQFtqydaG1JOLgfJqWSlDwvzaBrCx7mAAfdqVfjRgNhjh78Rz/Ug0AjYhKPfM8HqNTEpiTmLRaffLtEXcy1xh67s=
      userPassword: tuandai_test123
      orgCode: 1003
      userName: tuandai
      functionCodePre: QDP
      uri: tiyan.tianchengsys.com:4016/boss/uap
      key: AD905@!QLF-D25WEDA5!@#$%
  mongodb:
    socketKeepAlive: false
    maxWaitTime: 3500
    socketTimeout: 2500
    connectTimeout: 1000
    connectionsPerHost: 8
    threadsAllowedToBlockForConnectionMultiplier: 20
  redis:
    hostName: 10.110.1.240
    password: tuandai
    database: 4
    port: 6379
    pool:
      testOnBorrow: true
      maxIdle: 200
      minEvictableIdleTimeMillis: 60000
      timeBetweenEvictionRunsMillis: 30000
      maxTotal: 1024
      max-active: 200
    timeout: 1000
  email:
    password: 171717Xia
    port: 465
    host: smtp.exmail.qq.com
    username: xiayutai@hongte.info
eip:
  tc:
    blackList:
      privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJj0nhlKUwiBH0Xh0kAmuHMqBQWFLwbBqHEqAsFzJpAq/j9IeiMa4Y2o/uXckThzrmeA3pfVP4/1HtcLUrQ7u4qxs9c/xh2urtgz0jHw/ObMgx9mnNH7A5ED810uUnSD1fwtVKfmg+JSn6HY4bmZjZ6+7eZAwRWDgyWlBy2CDqdNAgMBAAECgYEAlqIhqUp3J6LyR4Iz65W2hURWma8mNwM1fe0ftaBP1B9jMLOSBUyN4VMTZRCpu+zBT5Gspd8PsBh4/NNb6cAB2vktgzd1w1I2aCxCprtpZ/9BJ255pAJnWKqWGar5w0wDeFfMrMSQWQubXw56k2kZQl4JOvZxIjty57V8yoNbL0kCQQDO6Ioc+MfOp7Al6vzjYvpPClm7jvAgV60INTPMaEkY/P46wIuYcOzb3KK84jOeEaA0quEx8gVpeuMYKS+zEQifAkEAvT8GEeSz0tY1neV7XIhCfsCX2YU6xeHQSVSndmI3Qw++LbSsK29Yk6S45YZhuQVCCxGN/tb2GHkRZ6b+QpjMkwJBAMpjKd3G92LMIgAlCDK/uUohPL66xWVNfaJ+r+ksxPudVGxRtPpq0zUIb2LE/GqMoSGDWH3LV8Hig0o51z+X1M8CQCzMcIln1FHCt6qLGmrLLsKGoOuzKDiTvhS9326czWwom+KB9IfLsfIxejuLVjLQVdP88doz1MnyTvZ0h5gIR9UCQFtqydaG1JOLgfJqWSlDwvzaBrCx7mAAfdqVfjRgNhjh78Rz/Ug0AjYhKPfM8HqNTEpiTmLRaffLtEXcy1xh67s=
      userPassword: tuandai_test123
      orgCode: 1003
      userName: tuandai
      functionCodePre: QDP
      uri: tiyan.tianchengsys.com:4016/boss/uap
      key: AD905@!QLF-D25WEDA5!@#$%
