from: uat

server:
  port: 9999

#密码包含 特殊符号不能用以下配置
#spring.data.mongodb.uri=mongodb://root:@123.57.7.179:27017/eip
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: 123456
      host: 10.110.1.240
      port: 27017
      database: EIP
#每个主机允许的连接数（每个主机的连接池大小），当连接池被用光时，会被阻塞住 ，默认为10-
eip:
  mongodb:
    connectionsPerHost: 8
#threads that can block if connectionsPerHost is 10, and threadsAllowedToBlockForConnectionMultiplier is 5,
# then 50 threads can block more than that and an exception will be throw
    threadsAllowedToBlockForConnectionMultiplier: 20
#在建立（打开）套接字连接时的超时时间（ms）
    connectTimeout: 1000
#被阻塞线程从连接池获取连接的最长等待时间（ms）
    maxWaitTime: 3500
#This controls whether or not to have socket keep alive turned on (SO_KEEPALIVE). defaults to false
    socketKeepAlive: false
#套接字超时时间;该值会被传递给Socket.setSoTimeout(int)。
    socketTimeout: 2500