eureka:
  instance:
    prefer-ip-address: true

feign: 
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 2000
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 150
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
          strategy: THREAD
      fallback:
         isolation:
          semaphore:
            maxConcurrentRequests: 1000
ribbon:  
  ReadTimeout: 10000  
  ConnectTimeout: 10000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 1000
zuul:
  SendErrorFilter: 
    post:
      disable: true
  retryable: true
  ResponseFilter: 
    post: 
      disable: true
  host:
    maxTotalConnections: 2000
    maxPerRouteConnections: 800
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  semaphore:
    maxSemaphores: 1500
  routes:
    #用户权限管理中心
    ussp-uc:
      path: /uc/**
      serviceId: ussp-uc-app
    #外部用户权限管理中心
    ussp-ouc:
      path: /ouc/**
      serviceId: ussp-ouc-app
    #用户账户与授权平台
    ussp-uaa:
      path: /uaa/**
      serviceId: ussp-uaa-app
      sensitiveHeaders: "*"
    #外联平台
    eip:
      path: /ht/**
      serviceId: eip-in
    #车全系统
    cisp-web-service:
      path: /admin/**
      serviceId: cisp-web-service
      sensitiveHeaders: "*"
    cisp-car-service:
      path: /car/**
      serviceId: cisp-car-service
    #额度系统
    clms-limit-service:
      path: /clms-limit-service/**
      serviceId: clms-limit-service
    clms-product-service:
      path: /clms-product-service/**
      serviceId: clms-product-service
    clms-codes-service:
      path: /clms-codes-service/**
      serviceId: clms-codes-service
    #风控系统
    risk-ui:
      path: /rule/ui/**
      serviceId: risk-ui
    rule-service:
      path: /rule/service/**
      serviceId: rule-service
    risk-activiti-service:
      path: /activiti/service/**
      serviceId: risk-activiti-service
    risk-activiti-extend:
      path: /activiti/extend/**
      serviceId: risk-activiti-extend
    risk-drools:
      path: /drools/**
      serviceId: risk-drools
    risk-eip:
      path: /risk/eip/**
      serviceId: risk-eip
    #核心账务
    cams-account-service:
      path: /cams/account/**
      serviceId: cams-account-service
    cams-ui:
      path: /cams/ui/**
      serviceId: cams-ui
    cams-account-service-mq:
      path: /cams/accountmq/**
      serviceId: cams-account-service

    #诉讼系统
    litigation-service:
      path: /lawService/**
      serviceId: litigation-service
    litigation-ui:
      path: /lawUi/**
      serviceId: litigation-ui
    #贷后系统
    alms-core-service:
      path: /alms/core/**
      serviceId: alms-core-service
    alms-timer-service:
      path: /alms/timer/**
      serviceId: alms-timer-service
    alms-open-service:
      path: /alms/open/**
      serviceId: alms-open-service

    ht:
      path: /ht/*
      serviceId: eip-in

    #报表平台
    rp-app-service:
      path: /rp-app-service/**
      serviceId: rp-app-service
      sensitiveHeaders: "*"
    rp-code-service:
      path: /rp-code-service/**
      serviceId: rp-code-service
    rp-ui-service:
      path: /rp-ui-service/**
      serviceId: rp-ui-service
    rp-birt-view:
      path: /rp/view/**
      serviceId: rp-birt-view
      sensitiveHeaders: "*"
    #微信公众号
    wx-app:
      path: /wx/app/**
      serviceId: wx-app
      sensitiveHeaders: "*"
    wx-ui:
      path: /wx/ui/**
      serviceId: wx-ui      
    #销售系统
    bm-core-service:
      path: /bm/core/**
      serviceId: bm-core-service
    bm-web-ui:
      path: /bm/ui/**
      serviceId: bm-web-ui
   #信贷系统
    cls-core-service:
      path: /cls/core/**
      serviceId: cls-core-service
    cls-interface-service:
      path: /cls/interface/**
      serviceId: cls-interface-service
    cls-file-service:
      path: /cls/file/**
      serviceId: cls-file-service  


ht:
  ignoreUrl: #不验证的url(可以使用通配符（*）),内部应用
     app: /wx/*,/ht/*  #系统级验证/web/
     web: /uaa/*,/ht/nologin/*,/admin/*,/car/*,/rule/ui/*,/cams/ui/*,/cams/accountmq/*,/lawUi/*,/alms/ui/*,/alms/core/downLoadController/*,/alms/core/car/download,/activiti/service/*,/lawUi/*,/rp-ui-service/*,/rp/view/*,/alms/open/carAuction/*,/bm/ui/*,/uc/web/*,/uc/user/getUserForOther,/uc/login/changePwd  #不需要验证token
     http: /uc/auth/loadBtnAndTab,/uc/auth/loadMenu,/rule/service/check/key,/rule/service/user/getUserInfo,/lawService/index/*,/lawService/ProcessApproveStepBar/getProcessWorkLogList,/uc/user/in/selfinfo,/uc/user/in/changePwd,/uc/user/in/selfinfo/set #验证token后放行
  outUrl: 
     permit: /clsPermit/*,/cls/core/nonLogin/*
     deny: /clsDeny/*
     
     
     
  rule:
    className: com.ht.ussp.gateway.app.rule.InstanceIdAndIPAddrRule #自定义路由策略
    
