server:
  port: 30111

gateway:
  security: 
    jwt: 
      tokenExpirationTime: 29  #分钟
      refreshTokenExpTime: 720
      tokenIssuer: qiuwenwu@hongte.info
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
 
ht:
  ignoreUrl: #不验证的url(可以使用通配符（*）)
     web: uc/echo,/admin/*,/car/* #不需要验证token
     http: /auth/loadBtnAndTab,/auth/loadMenu #需要验证token
 