spring:
    profiles.active: dev

---
spring:
  application:
    name: ussp-gateway-app
  cloud: 
    inetutils: 
      preferred-networks: 192.169.0
server:
  port: 9000
  
zuul:
  routes:
    ussp-risk:
      path: /risk/**
      serviceId: ussp-risk
    ussp-cisp:
      path: /car/**
      serviceId: ussp-cisp
    ussp-cams:
      path: /cams/**
      serviceId: ussp-cams
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
