server:
  port: 30111
feign:
  hystrix:  
    enabled: true
hystrix:
  threadpool: 
    default:
      coreSize: 2000
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
          strategy: THREAD
      fallback: 
         isolation:
          semaphore:
            maxConcurrentRequests: 1000

zuul:
  host:
    maxTotalConnections: 2000
    maxPerRouteConnections: 800
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  semaphore: 
    maxSemaphores: 1500
  routes:
    #用户权限管理中心
    ussp-uc:
      path: /uc/**
      serviceId: ussp-uc-app
    #外联平台
    eip:
      path: /ht/**
      serviceId: eip-in
    #车全系统
    cisp-web-service:
      path: /admin/**
      serviceId: cisp-web-service
      sensitiveHeaders: "*"
    cisp-car-service:
      path: /car/**
      serviceId: cisp-car-service
    #额度系统
    clms-limit-service:
      path: /clms-limit-service/**
      serviceId: clms-limit-service
    clms-product-service:
      path: /clms-product-service/**
      serviceId: clms-product-service
    clms-codes-service:
      path: /clms-codes-service/**
      serviceId: clms-codes-service
    #风控系统
    risk-ui:
      path: /rule/ui/**
      serviceId: risk-ui
      sensitiveHeaders: "*"
    rule-service:
      path: /rule/service/**
      serviceId: rule-service
      sensitiveHeaders: "*"
    risk-activiti:
      path: /activiti/**
      serviceId: risk-activiti-service
    risk-drools:
      path: /drools/**
      serviceId: risk-drools
    #核心账务
    cams-account-service:
      path: /cams/account/**
      serviceId: cams-account-service
    cams-ui:
      path: /cams/ui/**
      serviceId: cams-ui
    #诉讼系统
    litigation-service:
      path: /lawService/**
      serviceId: litigation-service
    litigation-ui:
      path: /lawUi/**
      serviceId: litigation-ui
   #贷后系统
    alms-core-service:
      path: /alms/core/**
      serviceId: alms-core-service
    alms-timer-service:
      path: /alms/timer/**
      serviceId: alms-timer-service
    report-birt-view:
      path: /rp/view/**
      serviceId: report-birt-view
      sensitiveHeaders: "*"
    rp-app-service:
      path: /rp-app-service/**
      serviceId: rp-app-service
      sensitiveHeaders: "*"
    rp-code-service:
      path: /rp-code-service/**
      serviceId: rp-code-service
    rp-ui-service:
      path: /rp-ui-service/**
      serviceId: rp-ui-service

gateway:
  security:
    jwt:
      tokenExpirationTime: 29  #分钟
      refreshTokenExpTime: 720
      tokenIssuer: qiuwenwu@hongte.info
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

ht:
  ignoreUrl: #不验证的url(可以使用通配符（*）)
     web: /uc/system/*,/ht/nologin/*,/admin/*,/car/*,/rule/ui/*,/cams/ui/*,/LawUi/*,/rp/view/*,/rp-ui-service/*, #不需要验证token
     http: /uc/auth/loadBtnAndTab,/uc/auth/loadMenu,/rule/service/check/key,/uc/user/in/selfinfo,/uc/user/in/changePwd,/uc/user/in/selfinfo/set,/rp/view/frameset #需要验证token
  rule:
    className: com.ht.ussp.gateway.app.rule.InstanceIdAndIPAddrRule #自定义路由策略

spring:
  servlet:
    multipart:
      max-file-size: 5MB