spring:
    profiles.active: uat

---
server:
  port: ${SERVER_PORT}
spring:
    profiles: uat
    application:
      name: ussp-gateway-app
    cloud: 
      inetutils: 
        preferred-networks: 10.200.1
 
zuul:
  routes:
    ussp-uc:
      path: /uc/**
      serviceId: ussp-uc-app
    ussp-risk:
      path: /risk/**
      serviceId: ussp-risk
    cisp-web-service:
      path: /admin/**
      serviceId: cisp-web-service
      sensitiveHeaders: "*"
    cisp-car-service:
      path: /car/**
      serviceId: cisp-car-service
    
      
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
      
gateway:
  security: 
    jwt: 
      tokenExpirationTime: 29  #分钟
      refreshTokenExpTime: 720
      tokenIssuer: qiuwenwu@hongte.info
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
 
ht:
  ignoreUrl: #不验证的url(可以使用通配符（*）)
     web: uc/echo #不需要验证token
     http: /auth/loadBtnAndTab,/auth/loadMenu #需要验证token
     
