spring:
  application:
    name: ussp-hystrix-app
  profiles:
    active: test
  rabbitmq:
    host: 10.110.1.240
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
      stream:
        rabbit:
          bindings:
            test:
              consumer:
                prefix: Z
        bindings:
          input:
            group: default

#turbine:
#  app-config: trace-1
#  cluster-name-expression: trace-1
#  stream:
#    port: 8900  # 这是turbine的端口即暴露监控数据的端口，跟server.port不同


#
server:
  port: 1301

turbine:
  stream:
    port: 8989



#turbine:
#  amqp:
#    port: 8989


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true


management:
  port: 10000
  security:
    enabled: false

