server:
  port: 30106
spring:
  profiles: dev
  rabbitmq:
    host: 172.16.200.111
    port: 5672
    username: admin
    password: hongte888
    virtual-host: /
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://172.16.200.102/config-dev/config.git
          search-paths: /*
          username: config-dev
          password: hongteconfig
security:
  user:
    name: root
    password: 123456
management:
  security:
    enabled: false

