server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ussp-config-app
  rabbitmq:
    host: ${RABBITMQ_HOST:10.100.1.80}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:tuandai888}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/data/rabbitmq-server}
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://${GIT_URI_IP:10.100.1.82}/root/config.git
          search-paths: ${GIT_SEARCH_PATH:/*}
          username: ${GIT_USERNAME:root}
          password: ${GIT_PASSWORD:tuandai888}
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_ADDRESS}      