server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ussp-config-app
  rabbitmq:
    host: ${RABBITMQ_HOST:10.100.8.57}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://${GIT_URI_IP:10.100.8.57}/root/config.git
          search-paths: ${GIT_SEARCH_PATH:/*}
          username: ${GIT_USERNAME:root}
          password: ${GIT_PASSWORD:tuandai888}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_ADDRESS}

security:
  user:
    name: root
    password: 123456

management:
  security:
    enabled: false
