server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ussp-config-app
  rabbitmq:
    host: 10.100.1.80
    port: 5672
    username: admin
    password: tuandai888
    virtual-host: /data/rabbitmq-server
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://10.100.1.82/root/config.git
          search-paths: /*
          username: root
          password: tuandai888
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_ADDRESS}

security:
  user:
    name: root
    password: 123456

management:
  security:
    enabled: false
