server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ussp-config-app
  profiles:
    active: UAT
  rabbitmq:
    host: ${RABBITMQ_IP}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    config:
      bus:
        trace:
          enabled: true
      server:
        git:
          uri: http://10.100.5.193:8000/root/config.git
          search-paths: /*
          username: root
          password: tuandai888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_ADDRESS}

security:
  user:
    name: root
    password: 123456

management:
  security:
    enabled: false

