server:
  port: 30106
spring:
  profiles: dev
  rabbitmq:
    host: 172.16.200.111
    port: 5672
    username: admin
    password: hongte888
    virtual-host: /
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: http://172.16.200.102/config-dev/config.git
          search-paths: /*
          username: config-dev
          password: hongteconfig

eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://172.16.200.110:30101/eureka/  # 闁板秶鐤嗗▔銊ュ斀娑擃厼绺緐rl
security:
  user:
    name: root
    password: 123456

management:
  security:
    enabled: false

