server:
  port: 30106
spring:
  application:
    name: ussp-config-app
eureka:
  instance:
    prefer-ip-address: true
security:
  user:
    name: root
    password: 123456

management:
  security:
    enabled: false