server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ussp-config-app
  rabbitmq:
    host: 10.100.8.57
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud: 
    config:
      bus:
        trace:
          enabled: true
      server:
        git:
          uri: http://120.79.193.248/root/config.git
          search-paths: /*
          username: root
          password: tuandai888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_ADDRESS}

security:
  user:
    name: root
    password: 123456

management:
  security:
    enabled: false
