spring:
  application:
    name: ussp-admin-app
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream
server:
  port: 9998


eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 1
  client: 
    serviceUrl: 
      defaultZone: http://localhost:30101/eureka/
      
management: 
  security:
    enabled: false