spring:
  application:
    name: trace-2
  profiles:
    active: test
  rabbitmq:
      host: 10.110.1.240
      port: 5672
      username: admin
      password: admin
      virtual-host: /
server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.110.1.240:10001/eureka/

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG



