server:
  port: 30201
spring:
  application:
    name: cisp-car-service
  cloud:
    config:
      overrideNone: true
  datasource:
    minIdle: 1
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.13.36:3306/cqgl?useUnicode=true&characterEncoding=UTF8
    password: 123456
    testOnBorrow: false
    maxOpenPreparedStatements: 20
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    name: test
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    username: root
sms:
  password: fQ8i461Q
  url: http://122.13.18.210:9051/api/v1.0.0/message/mass/send
  username: cqqc@dgtdw
logging:
  level:
    com:
      tdw:
        cams:
          account:
            mapper: debug
feign:
  hystrix:
    enabled: false
mybatis-plus:
  type-enums-package: com.ht.cisp.car.entity.enums
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    logic-not-delete-value: 1
    field-strategy: 2
    logic-delete-value: 0
    db-column-underline: true
    refresh-mapper: true
    id-type: 3
  type-aliases-package: com.ht.cisp.car.entity
aliyun:
  oss:
    accessKeyId: LTAIUB4RBQT03pJ6
    accessKeySecret: LoimODQpVCtOVldU9BZUtgXdZhe2kV
    roleArn: acs:ram::1191113840098299:role/aliyunosstokengeneratorrole
    roleSessionName: cisp_001
    policy: 231
swagger:
  service:
    name: cisp-car-service
    description: cisp-car-service后端服务接口
    developer: F1
  basepackage: com.ht.cisp.car
