spring:
    profiles.active: dev
---
server:
  port: 9999
spring:
    profiles: dev
    #指定使用sping的数据源
    datasource:
        url: jdbc:mysql://10.110.1.240:3306/BOA?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: tuandai_bm2015
    redis:
        database : 1
        host : 192.168.15.100
        password: 123456
        port : 6379
#        password : 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.110.1.240:10001/eureka/
ht.config.uc.api:
  synch: false #是否同步API资源到用户权限中心