server:
  port: 30126
spring:
  datasource:
    url: jdbc:mysql://172.16.200.111:3306/BOA?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: hongte888
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive : 20
    minIdle: 5
    validation-query: SELECT 1 FROM DUAL
    filters: stat,wall,log4j
    testOnBorrow: false
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=800
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
        ddl-auto: auto
        naming:
          physical-strategy: com.ht.ussp.uc.app.config.MySQLUpperCaseStrategy
    generate-ddl: true
  redis:
    database : 0
    host : 172.16.200.111
    port : 6379
    password : hongte888
    timeout : 3000  #毫秒
    pool :
      max-active : 1000
      max-wait : 10000  #等待可用连接的最大时间，超过该时间，将抛出异常，-1表示永不超时，单位毫秒
      max-idle : 20  #最大空闲连接，默认8
      min-idle : 5   #最小空闲连接，默认0
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
ht.config.uc.api:
  synch: false #是否同步API资源到用户权限中心
  isDeleteOld: false #是否删除旧资源，删除旧资源的同时，关联关系也将被删除
  packages: com.ht.ussp.uc.app #API资源扫描的包，可用多个，多个使用“,”分隔
  app: UC