spring:
    profiles.active: dev
    
---
server:
  port: 9999
spring:
    profiles: dev
    application:
      name: ussp-uc-app
    cloud: 
      inetutils: 
        preferred-networks: 192.169.0
    #指定使用sping的数据源
    datasource:
        url: jdbc:mysql://10.110.1.240:3306/BOA?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: tuandai_bm2015
        dbcp2:
          validation-query: SELECT 1
          test-while-idle: true
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: auto
            naming:
              physical-strategy: com.ht.ussp.uc.app.config.MySQLUpperCaseStrategy
        generate-ddl: true
    redis:
        database : 5
        host : 192.168.15.100
        port : 6379
        password : 123456
        timeout : 3000  #毫秒
        pool : 
            max-active : 1000
            max-wait : 10000  #等待可用连接的最大时间，超过该时间，将抛出异常，-1表示永不超时，单位毫秒
            max-idle : 20  #最大空闲连接，默认8
            min-idle : 5   #最小空闲连接，默认0
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.110.1.240:10001/eureka/
