spring:
    profiles.active: uat

---
server:
  port: ${SERVER_PORT}
spring:
    profiles: uat
    cloud:
      inetutils:
        preferred-networks: 10.200.1
    #指定使用sping的数据源
    datasource:
        url: jdbc:mysql://10.100.5.193:3306/BOA?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
#        password: tuandai_bm2015
        password: tuandai888
    redis:
        database : 1
        host : 10.100.5.193
        port : 6379
#        password : 123456
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}