spring:
    profiles.active: dev
---
server:
  port: 9999
spring:
    profiles: dev
    #指定使用sping的数据源
    datasource:
        url: jdbc:mysql://10.110.1.240:3306/BOA?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: tuandai_bm2015
    redis:
        database : 0
        host : 10.110.1.240
        port : 6379
        password : tuandai
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.110.1.240:10001/eureka/
ht.config.uc.api:
  synch: true #是否同步API资源到用户权限中心