server:
  port: 30136

spring:
  jackson:
    time-zone: Asia/Chongqing

#鉴权参数
uaa:
  security:
    jwt:
      tokenExpirationTime: 30  #内部应用token失效时间    单位：分钟
      refreshTokenExpTime: 720  #内部应用刷新token失效时间,单位：分钟  12小时
      appTokenTime: 365 #天，系统级鉴权token失效时间
      tokenIssuer: qiuwenwu@hongte.info
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
      outUserTokenTime: 1000  #外部用户token失效时间  单位：年，目前主要针对鸿特金服APP的需求
      outRefreshTokenExpTime: 129600  #90天，可保存到外部系统的数据库
      outTokenSigningKey: V6bEDZuckEx5DdCEFuyBO8oGHvIKSh
      
      
      
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 2000
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
          strategy: THREAD
      fallback:
         isolation:
          semaphore:
            maxConcurrentRequests: 1000
ribbon:  
  ReadTimeout: 10000  
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  ServerListRefreshInterval: 1000 
