server:
  port: 30136
  
  undertow:
    io-threads: 4
    worker-threads: 1000
  
spring:
  jackson:
    time-zone: Asia/Chongqing

uaa:
  security:
    jwt:
      tokenExpirationTime: 29  #分钟
      refreshTokenExpTime: 720
      appTokenTime: 365 #天
      tokenIssuer: qiuwenwu@hongte.info
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
      
      
ribbon:  
  ReadTimeout: 10000  
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1