/*
SQLyog 企业版 - MySQL GUI v8.14 
MySQL - 5.6.39 : Database - BOA
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`BOA` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;

USE `BOA`;

/*Table structure for table `DD_DEPT` */

DROP TABLE IF EXISTS `DD_DEPT`;

CREATE TABLE `DD_DEPT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEPTID` varchar(64) NOT NULL,
  `DEPTNAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PARENTID` varchar(64) DEFAULT NULL,
  `CREATE_OPERATOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `UPDATE_OPERATOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  `ORG_PATH` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `ORDERS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ID` (`ID`),
  KEY `DEPTID` (`DEPTID`,`PARENTID`)
) ENGINE=InnoDB AUTO_INCREMENT=12227 DEFAULT CHARSET=latin1;

/*Table structure for table `DD_DEPT_USER` */

DROP TABLE IF EXISTS `DD_DEPT_USER`;

CREATE TABLE `DD_DEPT_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `ORG_CODE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '机构编码',
  `EMAIL` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `ID_NO` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '身份证号码',
  `MOBILE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '手机号码',
  `CREATE_OPERATOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `UPDATE_OPERATOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  `JOB_NUMBER` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '工号',
  `POSITION` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '岗位名称中文',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=43511 DEFAULT CHARSET=latin1;

/*Table structure for table `HT_BOA_IN_APP` */

DROP TABLE IF EXISTS `HT_BOA_IN_APP`;

CREATE TABLE `HT_BOA_IN_APP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APP` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '系统编码',
  `NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
  `NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '中文名称',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `APP` (`APP`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='系统表';

/*Table structure for table `HT_BOA_IN_BM_ORG` */

DROP TABLE IF EXISTS `HT_BOA_IN_BM_ORG`;

CREATE TABLE `HT_BOA_IN_BM_ORG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '机构编码',
  `ORG_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称',
  `ORG_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称中文',
  `PARENT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '父机构编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `ORG_TYPE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '机构类型',
  `SEQUENCE` int(11) DEFAULT '0' COMMENT '顺序号',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`,`ORG_CODE`,`PARENT_ORG_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=647 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织机构表';

/*Table structure for table `HT_BOA_IN_BM_USER` */

DROP TABLE IF EXISTS `HT_BOA_IN_BM_USER`;

CREATE TABLE `HT_BOA_IN_BM_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `EMAIL` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `ID_NO` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证号码',
  `MOBILE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '手机号码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  `JOB_NUMBER` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '工号',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ID_NO` (`ID_NO`) USING BTREE,
  UNIQUE KEY `JOB_NUMBER` (`JOB_NUMBER`) USING BTREE,
  UNIQUE KEY `USER_ID` (`USER_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5915 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户表';

/*Table structure for table `HT_BOA_IN_CODE` */

DROP TABLE IF EXISTS `HT_BOA_IN_CODE`;

CREATE TABLE `HT_BOA_IN_CODE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `BIZ_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '业务编码',
  `NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
  `NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '中文名称',
  `TYPE_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '类型编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '根机构编码',
  `SEQUENCE` int(11) DEFAULT '0' COMMENT '顺序号',
  `STATUS` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='码表';

/*Table structure for table `HT_BOA_IN_CODE_TYPE` */

DROP TABLE IF EXISTS `HT_BOA_IN_CODE_TYPE`;

CREATE TABLE `HT_BOA_IN_CODE_TYPE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `TYPE_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '类型编码',
  `TYPE_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '类型名',
  `TYPE_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '类型中文名',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '根机构编码',
  `SEQUENCE` int(11) DEFAULT '0' COMMENT '顺序号',
  `PARENT_CODE` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '父类型编码',
  `APP` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统编码',
  `CODE_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '编码路径',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='码表类型';

/*Table structure for table `HT_BOA_IN_CONTRAST` */

DROP TABLE IF EXISTS `HT_BOA_IN_CONTRAST`;

CREATE TABLE `HT_BOA_IN_CONTRAST` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `type` varchar(255) COLLATE utf8_bin NOT NULL COMMENT '对照类型(10：组织机构；20：用户；30：岗位；)',
  `uc_business_id` varchar(64) COLLATE utf8_bin NOT NULL COMMENT 'UC系统业务ID',
  `dd_business_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '钉钉系统业务ID',
  `bm_business_id` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '信贷系统业务ID',
  `extend_business_id_1` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展业务ID1',
  `extend_business_id_2` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展业务ID2',
  `extend_business_id_3` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展业务ID3',
  `extend_business_id_4` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展业务ID4',
  `extend_business_id_5` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '扩展业务ID5',
  `contrast` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '对照人',
  `status` varchar(2) COLLATE utf8_bin DEFAULT NULL COMMENT '0:生效  1:未校对(未生效)',
  `contrast_datetime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '对照时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17935 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*Table structure for table `HT_BOA_IN_EXTEND_ROLE` */

DROP TABLE IF EXISTS `HT_BOA_IN_EXTEND_ROLE`;

CREATE TABLE `HT_BOA_IN_EXTEND_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `SUPER_ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '超级角色编码',
  `BASE_ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '基础角色编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `SUPER_ROLE_CODE` (`SUPER_ROLE_CODE`,`BASE_ROLE_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='扩展角色表';

/*Table structure for table `HT_BOA_IN_LOGIN` */

DROP TABLE IF EXISTS `HT_BOA_IN_LOGIN`;

CREATE TABLE `HT_BOA_IN_LOGIN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `LOGIN_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '登陆ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `PASSWORD` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
  `EFFECTIVE_DATE` datetime DEFAULT NULL COMMENT '密码生效时间',
  `PWD_EXP_DATE` datetime DEFAULT NULL COMMENT '密码失效时间',
  `FAILED_COUNT` int(11) DEFAULT NULL COMMENT '密码错误次数',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '状态: 0 正常 1初始密码 ',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `LOGIN_ID` (`LOGIN_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=41056 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='登录信息表';

/*Table structure for table `HT_BOA_IN_LOGIN_20180306` */

DROP TABLE IF EXISTS `HT_BOA_IN_LOGIN_20180306`;

CREATE TABLE `HT_BOA_IN_LOGIN_20180306` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `LOGIN_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '登陆ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `PASSWORD` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
  `EFFECTIVE_DATE` datetime DEFAULT NULL COMMENT '密码生效时间',
  `PWD_EXP_DATE` datetime DEFAULT NULL COMMENT '密码失效时间',
  `FAILED_COUNT` int(11) DEFAULT NULL COMMENT '密码错误次数',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `LOGIN_ID` (`LOGIN_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8202 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='登录信息表';

/*Table structure for table `HT_BOA_IN_OPERATOR_LOG` */

DROP TABLE IF EXISTS `HT_BOA_IN_OPERATOR_LOG`;

CREATE TABLE `HT_BOA_IN_OPERATOR_LOG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `ACTION_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '操作名称',
  `DEVICE_TYPE` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '设备类型',
  `RESULT` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '结果',
  `CLIENT_IP` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '客户端IP',
  `ACTION_TIME` datetime DEFAULT NULL COMMENT '发生时间',
  `DEVICE_NO` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '设备号',
  `APP` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '系统编码',
  `TYPE` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '日志类型',
  `ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构编码',
  `JOB_NUMBER` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '工号',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=946 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='操作日志';

/*Table structure for table `HT_BOA_IN_ORG` */

DROP TABLE IF EXISTS `HT_BOA_IN_ORG`;

CREATE TABLE `HT_BOA_IN_ORG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '机构编码',
  `ORG_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称',
  `ORG_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称中文',
  `PARENT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '父机构编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `ORG_TYPE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '机构类型',
  `DATA_SOURCE` int(32) DEFAULT '1' COMMENT '数据来源(1：用户权限系统；2：钉钉同步)',
  `SEQUENCE` int(11) DEFAULT '0' COMMENT '顺序号',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=18464 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织机构表';

/*Table structure for table `HT_BOA_IN_ORG_20180306` */

DROP TABLE IF EXISTS `HT_BOA_IN_ORG_20180306`;

CREATE TABLE `HT_BOA_IN_ORG_20180306` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '机构编码',
  `ORG_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称',
  `ORG_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称中文',
  `PARENT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '父机构编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `ORG_TYPE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '机构类型',
  `SEQUENCE` int(11) DEFAULT '0' COMMENT '顺序号',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=648 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织机构表';

/*Table structure for table `HT_BOA_IN_ORG_LOGO` */

DROP TABLE IF EXISTS `HT_BOA_IN_ORG_LOGO`;

CREATE TABLE `HT_BOA_IN_ORG_LOGO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构编码',
  `LOGO_IMG` blob COMMENT 'LOGO_IMG',
  `VERSION` decimal(5,0) DEFAULT NULL COMMENT '版本',
  `IMG_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '图片名称',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ORG_CODE` (`ORG_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='机构logo图片表';

/*Table structure for table `HT_BOA_IN_POSITION` */

DROP TABLE IF EXISTS `HT_BOA_IN_POSITION`;

CREATE TABLE `HT_BOA_IN_POSITION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `POSITION_CODE` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '岗位编号',
  `POSITION_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '岗位名称',
  `POSITION_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '岗位名称中文',
  `PARENT_ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '父机构编号',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '根机构编码',
  `SEQUENCE` int(11) DEFAULT NULL COMMENT '顺序号',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='岗位表';

/*Table structure for table `HT_BOA_IN_POSITION_ROLE` */

DROP TABLE IF EXISTS `HT_BOA_IN_POSITION_ROLE`;

CREATE TABLE `HT_BOA_IN_POSITION_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `POSITION_CODE` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '岗位编号',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '根机构编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='岗位角色关联表';

/*Table structure for table `HT_BOA_IN_POSITION_USER` */

DROP TABLE IF EXISTS `HT_BOA_IN_POSITION_USER`;

CREATE TABLE `HT_BOA_IN_POSITION_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `POSITION_CODE` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '岗位编号',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='岗位用户表';

/*Table structure for table `HT_BOA_IN_PWD_HIST` */

DROP TABLE IF EXISTS `HT_BOA_IN_PWD_HIST`;

CREATE TABLE `HT_BOA_IN_PWD_HIST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `PASSWORD` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '密码',
  `PWD_CRE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '密码建立时间',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=105 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='密码维护历史表';

/*Table structure for table `HT_BOA_IN_RESOURCE` */

DROP TABLE IF EXISTS `HT_BOA_IN_RESOURCE`;

CREATE TABLE `HT_BOA_IN_RESOURCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `RES_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '资源编码',
  `RES_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源英文名称',
  `RES_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源中文名称',
  `SEQUENCE` int(11) DEFAULT NULL COMMENT '顺序号',
  `RES_TYPE` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '资源类型',
  `RES_PARENT` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '父资源',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '状态（1，禁用，0，启用，2，隐藏）',
  `RES_ICON` blob COMMENT '图标',
  `FONT_ICON` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '字体图标',
  `RES_CONTENT` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '资源内容',
  `APP` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=7065 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='资源信息表';

/*Table structure for table `HT_BOA_IN_RESOURCE_copy` */

DROP TABLE IF EXISTS `HT_BOA_IN_RESOURCE_copy`;

CREATE TABLE `HT_BOA_IN_RESOURCE_copy` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `RES_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '资源编码',
  `RES_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源英文名称',
  `RES_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源中文名称',
  `SEQUENCE` int(11) DEFAULT NULL COMMENT '顺序号',
  `RES_TYPE` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '资源类型',
  `RES_PARENT` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '父资源',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '状态（1，禁用，0，启用，2，隐藏）',
  `RES_ICON` blob COMMENT '图标',
  `FONT_ICON` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '字体图标',
  `RES_CONTENT` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '资源内容',
  `APP` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6938 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='资源信息表';

/*Table structure for table `HT_BOA_IN_ROLE` */

DROP TABLE IF EXISTS `HT_BOA_IN_ROLE`;

CREATE TABLE `HT_BOA_IN_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `ROLE_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '角色英文名',
  `ROLE_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '角色中文名',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `APP` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '系统编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ROLE_CODE` (`ROLE_CODE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='角色表';

/*Table structure for table `HT_BOA_IN_ROLE_RES` */

DROP TABLE IF EXISTS `HT_BOA_IN_ROLE_RES`;

CREATE TABLE `HT_BOA_IN_ROLE_RES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `RES_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '资源编码',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=34178 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='角色资源表';

/*Table structure for table `HT_BOA_IN_USER` */

DROP TABLE IF EXISTS `HT_BOA_IN_USER`;

CREATE TABLE `HT_BOA_IN_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `EMAIL` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `ID_NO` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证号码',
  `MOBILE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '手机号码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  `JOB_NUMBER` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '工号',
  `DATA_SOURCE` int(32) NOT NULL DEFAULT '1' COMMENT '数据来源(1：用户权限系统；2：钉钉同步;3:信贷系统)',
  `USER_TYPE` varchar(2) COLLATE utf8_bin DEFAULT NULL COMMENT '用户类型',
  `IS_ORG_USER` int(11) NOT NULL DEFAULT '1' COMMENT '是否是组织用户(1：是 0：否)',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `USER_ID` (`USER_ID`) USING BTREE,
  UNIQUE KEY `EMAIL` (`EMAIL`),
  UNIQUE KEY `MOBILE` (`MOBILE`)
) ENGINE=InnoDB AUTO_INCREMENT=61273 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户表';

/*Table structure for table `HT_BOA_IN_USER_20180306` */

DROP TABLE IF EXISTS `HT_BOA_IN_USER_20180306`;

CREATE TABLE `HT_BOA_IN_USER_20180306` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '机构编码',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `EMAIL` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `ID_NO` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证号码',
  `MOBILE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '手机号码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  `JOB_NUMBER` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '工号',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ID_NO` (`ID_NO`) USING BTREE,
  UNIQUE KEY `JOB_NUMBER` (`JOB_NUMBER`) USING BTREE,
  UNIQUE KEY `USER_ID` (`USER_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5914 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户表';

/*Table structure for table `HT_BOA_IN_USER_APP` */

DROP TABLE IF EXISTS `HT_BOA_IN_USER_APP`;

CREATE TABLE `HT_BOA_IN_USER_APP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `APP` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统编码',
  `CONTROLLER` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '管理员',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=895 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户系统关联表';

/*Table structure for table `HT_BOA_IN_USER_APP_201803131715` */

DROP TABLE IF EXISTS `HT_BOA_IN_USER_APP_201803131715`;

CREATE TABLE `HT_BOA_IN_USER_APP_201803131715` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `APP` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统编码',
  `CONTROLLER` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '管理员',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=123 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户系统关联表';

/*Table structure for table `HT_BOA_IN_USER_ROLE` */

DROP TABLE IF EXISTS `HT_BOA_IN_USER_ROLE`;

CREATE TABLE `HT_BOA_IN_USER_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=734 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户角色关联表';

/*Table structure for table `HT_BOA_IN_USER_ROLE_201803131715` */

DROP TABLE IF EXISTS `HT_BOA_IN_USER_ROLE_201803131715`;

CREATE TABLE `HT_BOA_IN_USER_ROLE_201803131715` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ROOT_ORG_CODE` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=167 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户角色关联表';

/*Table structure for table `HT_BOA_ORG` */

DROP TABLE IF EXISTS `HT_BOA_ORG`;

CREATE TABLE `HT_BOA_ORG` (
  `ID` bigint(20) NOT NULL DEFAULT '0' COMMENT 'ID',
  `ORG_CODE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '机构编码',
  `ORG_NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称',
  `ORG_NAME_CN` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '机构名称中文',
  `PARENT_ORG_CODE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '父机构编码',
  `ROOT_ORG_CODE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '根机构编码',
  `ORG_PATH` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '机构路径',
  `ORG_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '机构类型',
  `SEQUENCE` int(11) DEFAULT '0' COMMENT '顺序号',
  `REMARK` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `CREATE_OPERATOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*Table structure for table `HT_BOA_OUT_APP` */

DROP TABLE IF EXISTS `HT_BOA_OUT_APP`;

CREATE TABLE `HT_BOA_OUT_APP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APP` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '系统编码',
  `NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
  `NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '中文名称',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `APP` (`APP`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='系统表';

/*Table structure for table `HT_BOA_OUT_DEVICE` */

DROP TABLE IF EXISTS `HT_BOA_OUT_DEVICE`;

CREATE TABLE `HT_BOA_OUT_DEVICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `DEVICE_NO` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '设备号',
  `IS_MASTER` int(11) DEFAULT NULL COMMENT '是否主设备',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='设备表';

/*Table structure for table `HT_BOA_OUT_LOGIN` */

DROP TABLE IF EXISTS `HT_BOA_OUT_LOGIN`;

CREATE TABLE `HT_BOA_OUT_LOGIN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `LOGIN_ID` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '登陆ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `PASSWORD` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
  `EFFECTIVE_DATE` datetime DEFAULT NULL COMMENT '密码生效时间',
  `PWD_EXP_DATE` datetime DEFAULT NULL COMMENT '密码失效时间',
  `FAILED_COUNT` int(11) DEFAULT NULL COMMENT '密码错误次数',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `LOGIN_ID` (`LOGIN_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='登陆信息表';

/*Table structure for table `HT_BOA_OUT_OPERATOR_LOG` */

DROP TABLE IF EXISTS `HT_BOA_OUT_OPERATOR_LOG`;

CREATE TABLE `HT_BOA_OUT_OPERATOR_LOG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `ACTION_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '操作名称',
  `DEVICE_TYPE` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '设备类型',
  `RESULT` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '结果',
  `CLIENT_IP` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '客户端IP',
  `ACTION_TIME` datetime DEFAULT NULL COMMENT '发生时间',
  `DEVICE_NO` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '设备号',
  `APP` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '系统编码',
  `TYPE` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '日志类型',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='操作日志';

/*Table structure for table `HT_BOA_OUT_PWD_HIST` */

DROP TABLE IF EXISTS `HT_BOA_OUT_PWD_HIST`;

CREATE TABLE `HT_BOA_OUT_PWD_HIST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `PASSWORD` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '密码',
  `PWD_CRE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '密码建立时间',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='密码维护历史表';

/*Table structure for table `HT_BOA_OUT_RESOURCE` */

DROP TABLE IF EXISTS `HT_BOA_OUT_RESOURCE`;

CREATE TABLE `HT_BOA_OUT_RESOURCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `RES_CODE` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源编码',
  `RES_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源英文名称',
  `RES_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '资源中文名称',
  `SEQUENCE` int(11) DEFAULT NULL COMMENT '顺序号',
  `RES_TYPE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '资源类型',
  `RES_PARENT` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '父资源',
  `REMARK` varchar(2000) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `RES_ICON` blob COMMENT '图标',
  `RES_CONTENT` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '资源内容',
  `APP` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '系统编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `RES_CODE` (`RES_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='资源信息表';

/*Table structure for table `HT_BOA_OUT_ROLE` */

DROP TABLE IF EXISTS `HT_BOA_OUT_ROLE`;

CREATE TABLE `HT_BOA_OUT_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `ROLE_NAME` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '角色英文名',
  `ROLE_NAME_CN` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '角色中文名',
  `STATUS` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ROLE_CODE` (`ROLE_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='角色表';

/*Table structure for table `HT_BOA_OUT_ROLE_RES` */

DROP TABLE IF EXISTS `HT_BOA_OUT_ROLE_RES`;

CREATE TABLE `HT_BOA_OUT_ROLE_RES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `RES_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '资源编码',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='角色资源表';

/*Table structure for table `HT_BOA_OUT_USER` */

DROP TABLE IF EXISTS `HT_BOA_OUT_USER`;

CREATE TABLE `HT_BOA_OUT_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `USER_NAME` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
  `EMAIL` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `ID_NO` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '身份证号码',
  `MOBILE` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '手机号码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `USER_NAME` (`USER_NAME`) USING BTREE,
  UNIQUE KEY `EMAIL` (`EMAIL`) USING BTREE,
  UNIQUE KEY `ID_NO` (`ID_NO`) USING BTREE,
  UNIQUE KEY `MOBILE` (`MOBILE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户表';

/*Table structure for table `HT_BOA_OUT_USER_APP` */

DROP TABLE IF EXISTS `HT_BOA_OUT_USER_APP`;

CREATE TABLE `HT_BOA_OUT_USER_APP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USER_ID` varchar(64) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  `APP` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统编码',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户系统关联表';

/*Table structure for table `HT_BOA_OUT_USER_ROLE` */

DROP TABLE IF EXISTS `HT_BOA_OUT_USER_ROLE`;

CREATE TABLE `HT_BOA_OUT_USER_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ROLE_CODE` varchar(128) COLLATE utf8_bin NOT NULL COMMENT '角色编码',
  `USER_ID` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '用户ID',
  `CREATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `CREATED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `JPA_VERSION` int(11) DEFAULT '0' COMMENT '乐观锁版本',
  `DEL_FLAG` int(11) DEFAULT '0' COMMENT '使用状态',
  `UPDATE_OPERATOR` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户角色关联表';

/*Table structure for table `test` */

DROP TABLE IF EXISTS `test`;

CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
