spring:
  application:
#    hostname: 10.110.1.240
    name: ussp-zipkin-app
#  datasource: 
#    url: jdbc:mysql://172.16.200.111:3306/temp?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: boa
#    password: ik2kvfbT
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema: classpath:/mysql_init.sql
  sleuth: 
    enabled: false
  rabbitmq:
    host: 172.16.200.111
    port: 5672
    username: admin
    password: hongte888
    virtual-host: /

#zipkin: 
#  storage: 
#    type: mysql
#  profiles:
#    active: test
#  rabbitmq:
#      host: 10.110.1.240
#      port: 5672
#      username: admin
#      password: admin
#      virtual-host: /
#  datasource:
#    schema: classpath:/mysql_init.sql
#    url: jdbc:mysql://10.110.1.240:3306/zipkin
#    username: root
#    password: tuandai_bm2015
#    continue-on-error: true
#    initialize: true
server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 1
    #instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:30101/eureka/
#zipkin:
#  storage:
#    type: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      hosts: http://172.16.200.111:9200
#      index: zipkin
#      index-shards: 5
#      index-replicas: 1


zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://172.16.200.111:9200
      username: elastic
      password: changeme
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1





