spring:
  application:
    hostname: 10.110.1.240
    name: ussp-zipkin-app
  profiles:
    active: test
  rabbitmq:
      host: 10.110.1.240
      port: 5672
      username: admin
      password: admin
      virtual-host: /
#  datasource:
#    schema: classpath:/mysql_init.sql
#    url: jdbc:mysql://10.110.1.240:3306/zipkin
#    username: root
#    password: tuandai_bm2015
#    continue-on-error: true
#    initialize: true
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://10.110.1.240:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1







