spring: 
  datasource:
    url: jdbc:mysql://10.110.1.240:3306/tuandai_bm_core?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: tuandai_bm2015
logging:
  level:
    - com.ht.cams.account.mapper: info   
ht.config.uc.api:
  synch: true
  packages: com.ht.cams.account.controller
  app: CAMS