spring:
  datasource:
    url: jdbc:mysql://10.110.1.240:3306/tuandai_bm_core?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: tuandai_bm2015
   

logging:
  level:
    - com.ht.cams.account.mapper: debug
    
ht.config.uc.api:
  synch: true #是否同步API资源到用户权限中心
  packages: com.ht.cams.account.controller #API资源扫描的包，可用多个，多个使用“,”分隔
  app: CAMS