spring:
  application:
    name: ussp-registry-app
  profiles:
    active: local
server:
  port: 30101
---
spring:
  profiles: local
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false  #关闭保护机制，以确保注册中心将不可用的实例正确剔除
    eviction-interval-timer-in-ms: 2000
    response-cache-update-interval-ms: 2000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
        defaultZone: http://localhost:${server.port}/eureka/      
        
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://172.16.200.110:${server.port}/eureka/
      
---
spring:
  profiles: sit
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://172.16.200.112:${server.port}/eureka/
---
spring:
  profiles: uat
server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

---
spring:
  profiles: prd

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}