server:
  port: 10003
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
