spring:
  application:
    name: ussp-registry-app
  profiles:
    active: native
 
---
spring:
  profiles: native
server:
  port: 30101
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: dev

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
      
---
spring:
  profiles: sit

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

---
spring:
  profiles: uat

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

---
spring:
  profiles: prd

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}