spring:
  application:
    name: ussp-registry-app
#  cloud: 
#    inetutils: 
#      preferred-networks: 192.169.0
server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
#       defaultZone: http://localhost:30101/eureka
   