spring:
  application:
    name: ussp-registry-app
  profiles:
    active: local
server:
  port: 30101
 
---
spring:
  profiles: local
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false  #关闭保护机制，以确保注册中心将不可用的实例正确剔除
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
        defaultZone: http://localhost:${server.port}/eureka/
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:${server.port}/eureka/
      
---
spring:
  profiles: sit
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:${server.port}/eureka/

---
spring:
  profiles: uat

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}

---
spring:
  profiles: prd

server:
  port: ${SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}