ALTER TABLE `HT_BOA_IN_CONTRAST`
ADD COLUMN `status`  varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '0:生效  1:未校对(未生效)' AFTER `contrast`;

ALTER TABLE `DD_DEPT_USER`
ADD INDEX `ID` (`ID`) ;

ALTER TABLE `DD_DEPT`
ADD UNIQUE INDEX `ID` (`ID`) ;

ALTER TABLE `HT_BOA_IN_BM_ORG`
ADD INDEX `ID` (`ID`, `ORG_CODE`, `PARENT_ORG_CODE`) ;

ALTER TABLE `DD_DEPT`
ADD INDEX `DEPTID` (`DEPTID`, `PARENTID`) ;


ALTER TABLE `HT_BOA_IN_USER`
MODIFY COLUMN `DATA_SOURCE`  int(32) NOT NULL DEFAULT 1 COMMENT '数据来源(1：用户权限系统；2：钉钉同步;3:信贷系统)' AFTER `JOB_NUMBER`;

