ALTER TABLE `HT_BOA_IN_CONTRAST`
ADD COLUMN `status`  varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '0:生效  1:未校对(未生效)' AFTER `contrast`;

ALTER TABLE `HT_BOA_IN_BM_ORG`
ADD INDEX `ID` (`ID`, `ORG_CODE`, `PARENT_ORG_CODE`) ;

ALTER TABLE `HT_BOA_IN_USER`
MODIFY COLUMN `DATA_SOURCE`  int(32) NOT NULL DEFAULT 1 COMMENT '数据来源(1：用户权限系统；2：钉钉同步;3:信贷系统)' AFTER `JOB_NUMBER`;

ALTER TABLE `HT_BOA_IN_LOGIN`
MODIFY COLUMN `STATUS`  varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '状态: 0 正常  1禁用 2离职  4冻结 5锁定' AFTER `FAILED_COUNT`;

ALTER TABLE `HT_BOA_IN_RESOURCE`
ADD UNIQUE INDEX `RES_CODE` (`RES_CODE`) ;

ALTER TABLE `HT_BOA_IN_LOGIN`
MODIFY COLUMN `STATUS`  varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '状态: 0 正常 1初始密码  ' AFTER `FAILED_COUNT`;

ALTER TABLE `HT_BOA_IN_USER`
ADD COLUMN `STATUS`  varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '状态: 0 正常 1初始密码  ' AFTER `IS_ORG_USER`;


ALTER TABLE `ht_boa_in_user`
ADD COLUMN `STATUS`  varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '状态: 0 正常 2离职' AFTER `IS_ORG_USER`;

UPDATE  HT_BOA_IN_LOGIN set STATUS='1' WHERE PASSWORD='$2a$10$52b2WeWW1uqhY.no7Q0V7OSDcYESKYfBf.hZ2FVjBW9m0HJcIdnKy'