server:
  port: ${SERVER_PORT}
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: clms-product-service
  rabbitmq:
    host: 10.100.8.57
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://10.100.5.193:3306/clms?characterEncoding=utf8&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tuandai888
    tomcat:
      max-active: 3
      max-idle: 2
      min-idle: 1
      initial-size: 3
      min-evictable-idle-time-millis: 10000
  messages:
    basename: i18n/messages
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  config: classpath:log4j2.xml
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
# 服务下的自定义配置变量在这里
clms:
  microser:
    codeser: clms-codes-service
ht.config.uc.api:
  synch: true
  package: com.ht.clms.product.resource;
  app: CL