server:
  port: ${SERVER_PORT}
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: clms-codes-service
  rabbitmq:
    host: 10.100.8.57
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://10.100.5.193:3306/clms?characterEncoding=utf8&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tuandai888
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true