server:
  port: 8020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
spring:
  rabbitmq:
    host: 10.110.1.240
    port: 5672
    username: admin
    password: admin
    virtual-host: /
#logging:
#  level:
#    root: INFO
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.springframework.cloud.sleuth: DEBUG

